###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/{{id}}

###
POST http://localhost:3000/posts
Content-Type: application/json

{
	"title": "Sample",
	"conetent": "Body text",
	"sender": "You"
}

###
PUT http://localhost:3000/posts/{{id}}
Content-Type: application/json

{
	"title": "Updated title"
}

